services:

  app:
    container_name: qa-angular-playwright-app
    build:
      context: .
      dockerfile: app/Dockerfile.app
    ports:
      - "4200:80"


  e2e:
    container_name: qa-angular-playwright-e2e
    build:
      context: .
      dockerfile: app/Dockerfile.e2e
    depends_on:
      app:
        condition: service_healthy
    environment:
      BASE_URL: "http://app:80"
      DOCKER: "true"
      CI: "true"
    volumes:
      - ./artifacts/test-results:/work/test-results
      - ./artifacts/playwright-report:/work/playwright-report
      - ./artifacts/blob-report:/work/blob-report
    shm_size: "1gb"


  lighthouse:
    container_name: qa-angular-playwright-lighthouse
    build:
      context: .
      dockerfile: Dockerfile.lighthouse
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./artifacts/lighthouse:/reports
      - ./app/performance/lighthouse-budget.json:/budget.json
    command: >
      sh -c "lighthouse http://app:80/login --only-categories=performance --budgets-path=/budget.json --chrome-flags='--headless --no-sandbox --disable-dev-shm-usage' --output=json --output-path=/reports/login.json --quiet;
             lighthouse http://app:80/dashboard --only-categories=performance --budgets-path=/budget.json --chrome-flags='--headless --no-sandbox --disable-dev-shm-usage' --output=json --output-path=/reports/dashboard.json --quiet"





